version: '3'

services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
  
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=test
    ports:
      - "5432:5432"

volumes:
  postgres_data: